In [7]:
import pickle
import numpy as np
import pandas as pd
import polars as pl
import scanpy as sc

In [8]:
df_real = pl.read_parquet("/home/wzc26/work/vcc/nbglm/data/all_de_cache/real_de.parquet")

In [10]:
df = pd.read_csv("/home/wzc26/work/vcc/nbglm/outputs/gpm_default__20251009_150340/metrics/de.csv")
df_wrong = df[df['gt_significant']!=df['pred_significant']]

In [ ]:
df_wrong

gene   pert  gt_pvals    gt_fdr  gt_logfoldchanges  \
1        NOC2L   MTA1  0.330293  0.686575           0.030344   
5         HES4   MTA1  0.969067  1.000000           0.052484   
6        ISG15   MTA1  0.807070  0.960492          -0.014712   
7         AGRN   MTA1  0.131783  0.412016           0.011119   
18       ACAP3   MTA1  0.118644  0.386109          -0.049633   
...        ...    ...       ...       ...                ...   
542385  NLGN4Y  SALL4  0.147993  0.442046          -0.111007   
542386   KDM5D  SALL4  0.337016  0.693490           0.047222   
542394  MT-ND3  SALL4  0.312599  0.668467           0.065208   
542398  MT-ND6  SALL4  0.009687  0.062799           0.269046   
542399  MT-CYB  SALL4  0.068515  0.269675           0.250105   

        prediction_pvals  prediction_fdr  prediction_logfoldchanges  \
1           9.272703e-08    4.051747e-07                   0.146240   
5           5.806111e-03    1.461993e-02                   0.938944   
6           9.106220e-03    2.210597e-02                   0.066071   
7           7.114760e-10    3.631018e-09                  -0.058592   
18          8.164828e-04    2.352474e-03                   0.082777   
...                  ...             ...                        ...   
542385      5.603695e-05    1.876339e-04                   0.268803   
542386      2.326162e-09    1.145656e-08                   0.304874   
542394      4.709666e-17    3.549871e-16                   0.333829   
542398      5.541991e-19    4.558307e-18                   0.590069   
542399      1.959819e-19    1.643662e-18                   0.680293   

        gt_significant  pred_significant  
1                False              True  
5                False              True  
6                False              True  
7                False              True  
18               False              True  
...                ...               ...  
542385           False              True  
542386           False              True  
542394           False              True  
542398           False              True  
542399           False              True  

[232085 rows x 10 columns]

In [15]:
import polars as pl

alpha = 0.01  # 显著性阈值

genes_never_sig = (
    df_real.lazy()
      .group_by("feature")
      .agg([
          (pl.col("fdr") < alpha).any().alias("any_sig"),       # 是否在任一target下显著
          pl.n_unique("target").alias("n_targets"),              # 该基因被测试的target数
          pl.min("fdr").alias("min_fdr")                         # 观察到的最小FDR（越大越“不变”）
      ])
      .filter(pl.col("any_sig") == False)                        # 从未显著
      .select(["feature", "n_targets", "min_fdr"])
      .collect()
)


In [16]:
genes_never_sig

shape: (564, 3)
┌─────────┬───────────┬──────────┐
│ feature ┆ n_targets ┆ min_fdr  │
│ ---     ┆ ---       ┆ ---      │
│ cat     ┆ u32       ┆ f32      │
╞═════════╪═══════════╪══════════╡
│ OOSP1   ┆ 150       ┆ 0.077059 │
│ H3F3B   ┆ 150       ┆ 0.036897 │
│ HK3     ┆ 150       ┆ 0.031943 │
│ SCRT2   ┆ 150       ┆ 0.010208 │
│ CYP3A43 ┆ 150       ┆ 0.035058 │
│ …       ┆ …         ┆ …        │
│ ZNF705A ┆ 150       ┆ 0.034602 │
│ ACOD1   ┆ 150       ┆ 1.0      │
│ FOXD4L6 ┆ 150       ┆ 0.033043 │
│ OR5H14  ┆ 150       ┆ 0.082387 │
│ OVOL3   ┆ 150       ┆ 0.016961 │
└─────────┴───────────┴──────────┘

In [14]:
genes_never_sig.write_csv("genes_never_sig.csv")

In [17]:
wrong_gene=[]
for gene in genes_never_sig['feature']:
    if gene in df_wrong['gene'].values:
        wrong_gene.append(gene)
len(wrong_gene)

406

In [ ]:
import pandas as pd
df = pd.read_csv("/home/wzc26/work/vcc/nbglm/outputs/poisson_reg_test__20251009_142752/metrics/de.csv")
df = pd.read_csv("/home/wzc26/work/vcc/nbglm/outputs/gpm_default__20251009_150340/metrics/de.csv")
S = ((df.gt_significant) & (df.pred_significant)).sum()
V = ((~df.gt_significant) & (df.pred_significant)).sum()
T = ((df.gt_significant) & (~df.pred_significant)).sum()
U = ((~df.gt_significant) & (~df.pred_significant)).sum()

m  = S+T+U+V
R  = S+V
ppv = S / R if R else 0.0
tpr = S / (S+T) if (S+T) else 0.0
fdr = V / R if R else 0.0


In [ ]:
import pandas as pd
import numpy as np
import pandas as pd
df = pd.read_csv("/home/wzc26/work/vcc/nbglm/outputs/poisson_reg_test__20251009_142752/metrics/de.csv")
df = pd.read_csv("/home/wzc26/work/vcc/nbglm/outputs/gpm_default__20251009_150340/metrics/de.csv")
S = ((df.gt_significant) & (df.pred_significant)).sum()
V = ((~df.gt_significant) & (df.pred_significant)).sum()
T = ((df.gt_significant) & (~df.pred_significant)).sum()
U = ((~df.gt_significant) & (~df.pred_significant)).sum()

m  = S+T+U+V
R  = S+V
ppv = S / R if R else 0.0
tpr = S / (S+T) if (S+T) else 0.0
fdr = V / R if R else 0.0
# ---- 1) 四格表（Confusion table）与总体指标 ----
# 行：Pred (是否判为显著)；列：GT (真实是否显著/差异)
ct = pd.crosstab(
    df['pred_significant'], df['gt_significant'],
    rownames=['Pred (reject H0)'], colnames=['GT (HA true)']
).reindex(index=[True, False], columns=[True, False], fill_value=0)

# 统一命名方便阅读
ct.index = ['Pred: significant', 'Pred: non-significant']
ct.columns = ['GT: significant', 'GT: non-significant']

# 取四个格子
S = int(ct.loc['Pred: significant', 'GT: significant'])      # True Positive
V = int(ct.loc['Pred: significant', 'GT: non-significant'])  # False Positive (Type I)
T = int(ct.loc['Pred: non-significant', 'GT: significant'])  # False Negative (Type II)
U = int(ct.loc['Pred: non-significant', 'GT: non-significant'])  # True Negative

m  = S + V + T + U
R  = S + V          # 被拒绝的原假设 (rejections)
m0 = U + V          # 真实原假设数 (true nulls)

def sdiv(a, b):
    return float(a) / float(b) if b else 0.0

overall_metrics = pd.Series({
    'TP (S)': S,
    'FP (V)': V,
    'FN (T)': T,
    'TN (U)': U,
    'm (total)': m,
    'R (rejections)': R,
    'm0 (true nulls)': m0,
    'Precision / PPV': sdiv(S, S+V),
    'Recall / TPR / Power': sdiv(S, S+T),
    'FDR (FDP)': sdiv(V, R),           # 约定 R=0 时取 0
    'FNR': sdiv(T, S+T),
    'Accuracy': sdiv(S+U, m),
    'F1': sdiv(2*(sdiv(S, S+V)*sdiv(S, S+T)), (sdiv(S, S+V)+sdiv(S, S+T))) if (S+V) and (S+T) else 0.0
})

display(ct)
display(overall_metrics.to_frame('value'))

# ---- 2) 按 pert 分组统计与指标 ----
def counts_metrics(g: pd.DataFrame) -> pd.Series:
    ctab = pd.crosstab(g['pred_significant'], g['gt_significant'])
    # 防止缺列缺行
    s = int(ctab.get(True, {}).get(True, 0))
    v = int(ctab.get(True, {}).get(False, 0))
    t = int(ctab.get(False, {}).get(True, 0))
    u = int(ctab.get(False, {}).get(False, 0))
    m  = s+v+t+u
    r  = s+v
    return pd.Series({
        'TP (S)': s, 'FP (V)': v, 'FN (T)': t, 'TN (U)': u,
        'm': m, 'R': r, 'm0': u+v,
        'PPV': sdiv(s, r),
        'TPR': sdiv(s, s+t),
        'FDR': sdiv(v, r),
        'FNR': sdiv(t, s+t),
        'Accuracy': sdiv(s+u, m),
        'F1': sdiv(2*(sdiv(s, r)*sdiv(s, s+t)), (sdiv(s, r)+sdiv(s, s+t))) if r and (s+t) else 0.0
    })

by_pert = df.groupby('pert', sort=False).apply(counts_metrics)
# 可按需要排序，比如按 FDR 升序或 TPR 降序
by_pert_sorted = by_pert.sort_values(['FDR','TPR'], ascending=[True, False])

display(by_pert_sorted)


GT: significant  GT: non-significant
Pred: significant                41560               185630
Pred: non-significant            37468               277742

value
TP (S)                 41560.000000
FP (V)                185630.000000
FN (T)                 37468.000000
TN (U)                277742.000000
m (total)             542400.000000
R (rejections)        227190.000000
m0 (true nulls)       463372.000000
Precision / PPV            0.182931
Recall / TPR / Power       0.525890
FDR (FDP)                  0.817069
FNR                        0.474110
Accuracy                   0.588684
F1                         0.271441

/mnt/nvme0n1/users/wzc26/.tmp/ipykernel_2963900/3721399715.py:80: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  by_pert = df.groupby('pert', sort=False).apply(counts_metrics)


TP (S)  FP (V)   FN (T)   TN (U)        m       R       m0       PPV  \
pert                                                                            
CASP2     544.0   116.0  11815.0   5605.0  18080.0   660.0   5721.0  0.824242   
FOXH1    1887.0   411.0   9805.0   5977.0  18080.0  2298.0   6388.0  0.821149   
UQCRQ    2757.0   858.0   7613.0   6852.0  18080.0  3615.0   7710.0  0.762656   
POLB      790.0   288.0   9470.0   7532.0  18080.0  1078.0   7820.0  0.732839   
CLDN7    1184.0   464.0   7933.0   8499.0  18080.0  1648.0   8963.0  0.718447   
TFAM     3208.0  1451.0   5104.0   8317.0  18080.0  4659.0   9768.0  0.688560   
SSBP1    2128.0   963.0   5441.0   9548.0  18080.0  3091.0  10511.0  0.688450   
ACVR1B   1045.0   508.0   7361.0   9166.0  18080.0  1553.0   9674.0  0.672891   
MTA1     1838.0   894.0   6185.0   9163.0  18080.0  2732.0  10057.0  0.672767   
LRPPRC   3025.0  1482.0   5289.0   8284.0  18080.0  4507.0   9766.0  0.671178   
ZNF714    196.0   103.0  12009.0   5772.0  18080.0   299.0   5875.0  0.655518   
HMGB2    1288.0   680.0   6325.0   9787.0  18080.0  1968.0  10467.0  0.654472   
LZTR1    3622.0  1929.0   5136.0   7393.0  18080.0  5551.0   9322.0  0.652495   
PRCP      318.0   175.0   8445.0   9142.0  18080.0   493.0   9317.0  0.645030   
IRF3      198.0   109.0  11448.0   6325.0  18080.0   307.0   6434.0  0.644951   
PLCB3     242.0   175.0   9468.0   8195.0  18080.0   417.0   8370.0  0.580336   
SIX4      478.0   432.0   6981.0  10189.0  18080.0   910.0  10621.0  0.525275   
METTL17  2042.0  1940.0   2892.0  11206.0  18080.0  3982.0  13146.0  0.512808   
SIN3B    3804.0  4039.0   2202.0   8035.0  18080.0  7843.0  12074.0  0.485018   
SALL4    1776.0  1974.0   4283.0  10047.0  18080.0  3750.0  12021.0  0.473600   
CLDN6     230.0   260.0   5694.0  11896.0  18080.0   490.0  12156.0  0.469388   
PHF14     869.0  1006.0   4226.0  11979.0  18080.0  1875.0  12985.0  0.463467   
XRCC4     781.0  1070.0   3640.0  12589.0  18080.0  1851.0  13659.0  0.421934   
TAF13    1668.0  2689.0   3389.0  10334.0  18080.0  4357.0  13023.0  0.382832   
PMS1       81.0   147.0  10662.0   7190.0  18080.0   228.0   7337.0  0.355263   
TGFBR2   1495.0  3504.0   1978.0  11103.0  18080.0  4999.0  14607.0  0.299060   
RNF20    1510.0  3544.0   3100.0   9926.0  18080.0  5054.0  13470.0  0.298773   
SUPT4H1  2184.0  5183.0   1589.0   9124.0  18080.0  7367.0  14307.0  0.296457   
SDC1      295.0   831.0   2536.0  14418.0  18080.0  1126.0  15249.0  0.261989   
KDR        77.0   243.0   3611.0  14149.0  18080.0   320.0  14392.0  0.240625   

              TPR       FDR       FNR  Accuracy        F1  
pert                                                       
CASP2    0.044017  0.175758  0.955983  0.340100  0.083570  
FOXH1    0.161392  0.178851  0.838608  0.434956  0.269764  
UQCRQ    0.265863  0.237344  0.734137  0.531471  0.394280  
POLB     0.076998  0.267161  0.923002  0.460288  0.139354  
CLDN7    0.129867  0.281553  0.870133  0.535564  0.219972  
TFAM     0.385948  0.311440  0.614052  0.637445  0.494642  
SSBP1    0.281147  0.311550  0.718853  0.645796  0.399250  
ACVR1B   0.124316  0.327109  0.875684  0.564768  0.209860  
MTA1     0.229091  0.327233  0.770909  0.608462  0.341795  
LRPPRC   0.363844  0.328822  0.636156  0.625498  0.471882  
ZNF714   0.016059  0.344482  0.983941  0.330088  0.031350  
HMGB2    0.169184  0.345528  0.830816  0.612555  0.268865  
LZTR1    0.413565  0.347505  0.586435  0.609237  0.506255  
PRCP     0.036289  0.354970  0.963711  0.523230  0.068712  
IRF3     0.017002  0.355049  0.982998  0.360785  0.033130  
PLCB3    0.024923  0.419664  0.975077  0.466648  0.047793  
SIX4     0.064084  0.474725  0.935916  0.589989  0.114231  
METTL17  0.413863  0.487192  0.586137  0.732743  0.458053  
SIN3B    0.633367  0.514982  0.366633  0.654812  0.549354  
SALL4    0.293118  0.526400  0.706882  0.653927  0.362116  
CLDN6    0.038825  0.530612  0.961175  0.670686  0.071718  
PHF14    0.170559  0.536533  0.82944

In [ ]:
import torch
pt = torch.load("/home/wzc26/work/vcc/nbglm/outputs/MLP_TRY/poisson_mlp_1L_512H_0.05D_Residual_0.2init__20251010_182939/ckpt/model.pt")

In [ ]:
pt['state_dict']

OrderedDict([('K',
              tensor([[ 0.0028,  0.0103, -0.0539,  ...,  0.0469, -0.0155, -0.0386],
                      [ 0.0558, -0.0185,  0.0160,  ...,  0.0046,  0.0240, -0.0073],
                      [ 0.0433,  0.0591,  0.0322,  ..., -0.0508,  0.0111,  0.0385],
                      ...,
                      [ 0.0315,  0.0508, -0.0573,  ..., -0.0243,  0.0391,  0.0579],
                      [-0.0186, -0.0089, -0.0280,  ..., -0.0410,  0.0271, -0.0595],
                      [-0.0561,  0.0375,  0.0420,  ..., -0.0324,  0.0403,  0.0060]],
                     device='cuda:0')),
             ('bias',
              tensor([ 5.4907e-05, -9.5697e-02, -6.2402e-02,  ...,  6.4616e-02,
                       1.5522e-01,  1.1947e-01], device='cuda:0')),
             ('delta_log_mu_scaler', tensor(0.6948, device='cuda:0')),
             ('G_scaler', tensor(0.0634, device='cuda:0')),
             ('P_scaler', tensor(0.1017, device='cuda:0')),
             ('G',
              tensor([[-9.982